name: Deploy to Ionos

on:
  push:
    branches:
      - master

jobs:
  sftp-deploy:
    name: SFTP deploy static files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to Ionos via SFTP (lftp)
        env:
          SFTP_HOST: ${{ secrets.FTP_HOST }}
          SFTP_USER: ${{ secrets.FTP_USER }}
          SFTP_PASS: ${{ secrets.FTP_PASSWORD }}
          SFTP_DIR:  ${{ secrets.FTP_SERVER_DIR }}
        run: |
          lftp -u "$SFTP_USER","$SFTP_PASS" "sftp://$SFTP_HOST" << EOF
          set sftp:auto-confirm yes
          set net:max-retries 3
          set xfer:log yes
          echo "=== ROOT LISTING ==="
          ls
          echo "=== CHANGING TO: $SFTP_DIR ==="
          cd $SFTP_DIR
          echo "=== DIR LISTING AFTER CD ==="
          ls
          mput index.html style.css app.js frames.js
          echo "=== LISTING AFTER UPLOAD ==="
          ls
          quit
          EOF
