name: Deploy to Ionos

on:
  push:
    branches:
      - master

jobs:
  sftp-deploy:
    name: SFTP deploy static files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Ionos via SFTP
        env:
          SFTP_HOST: ${{ secrets.FTP_HOST }}
          SFTP_USER: ${{ secrets.FTP_USER }}
          SFTP_PASS: ${{ secrets.FTP_PASSWORD }}
          SFTP_DIR:  ${{ secrets.FTP_SERVER_DIR }}
        run: |
          sshpass -p "$SFTP_PASS" sftp \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o Port=22 \
            -o PubkeyAuthentication=no \
            -o PreferredAuthentications=password \
            -b - \
            "$SFTP_USER@$SFTP_HOST" << EOF
          cd $SFTP_DIR
          put index.html
          put style.css
          put app.js
          put frames.js
          EOF
